# -*- mode: python ; coding: utf-8 -*-


a = Analysis(  # type: ignore
    ['Circle_Nom.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('image/others/icon.ico', 'image/others'),
        ('sound/effects/nom_1.mp3', 'sound/effects'),
        ('sound/effects/nom_2.mp3', 'sound/effects'),
        ('sound/effects/nom_3.mp3', 'sound/effects'),
        ('sound/effects/nom_4.mp3', 'sound/effects'),
        ('sound/effects/nom_5.mp3', 'sound/effects'),
        ('sound/themes/theme_song_1.mp3', 'sound/themes'),
        ('sound/themes/theme_song_2.mp3', 'sound/themes'),
        ('sound/themes/theme_song_3.mp3', 'sound/themes'),
        ('sound/themes/theme_song_4.mp3', 'sound/themes'),
        ('sound/themes/theme_song_5.mp3', 'sound/themes'),
        ('sound/themes/theme_song_6.mp3', 'sound/themes'),
        ('sound/themes/theme_song_7.mp3', 'sound/themes'),
        ('sound/themes/theme_song_8.mp3', 'sound/themes'),
        ('sound/themes/theme_song_9.mp3', 'sound/themes'),
        ('sound/themes/theme_song_10.mp3', 'sound/themes'),
        ('sound/themes/theme_song_11.mp3', 'sound/themes'),
        ('sound/themes/theme_song_12.mp3', 'sound/themes'),
        ('sound/themes/theme_song_13.mp3', 'sound/themes'),
        ('sound/themes/theme_song_14.mp3', 'sound/themes'),
        ('sound/themes/theme_song_15.mp3', 'sound/themes'),
        ('sound/themes/theme_song_16.mp3', 'sound/themes'),
        ('image/backgrounds/background_image_1.jpg', 'image/backgrounds'),
        ('image/backgrounds/background_image_2.jpg', 'image/backgrounds'),
        ('image/backgrounds/background_image_3.jpg', 'image/backgrounds'),
        ('image/bar/hunger_bar_inner.png', 'image/bar'),
        ('image/bar/hunger_bar_outer.png', 'image/bar'),
        ('image/prey/glowing_sandwich.png', 'image/prey'),
        ('image/prey/prey_image_1.png', 'image/prey'),
        ('image/prey/prey_image_2.png', 'image/prey'),
        ('image/prey/prey_image_3.png', 'image/prey'),
        ('image/prey/prey_image_4.png', 'image/prey'),
        ('image/prey/prey_image_5.png', 'image/prey'),
        ('image/prey/prey_image_6.png', 'image/prey'),
        ('image/prey/prey_image_7.png', 'image/prey'),
        ('image/prey/prey_image_8.png', 'image/prey'),
        ('image/prey/prey_image_9.png', 'image/prey'),
        ('image/prey/prey_image_10.png', 'image/prey'),
        ('image/player_alive/player_image_1.png', 'image/player_alive'),
        ('image/player_alive/player_image_2.png', 'image/player_alive'),
        ('image/player_alive/player_image_3.png', 'image/player_alive'),
        ('image/player_dead/player_image_1_dead.png', 'image/player_dead'),
        ('image/player_dead/player_image_2_dead.png', 'image/player_dead'),
        ('image/player_dead/player_image_3_dead.png', 'image/player_dead'),
    ],
    hiddenimports=['pygame', 'gif_pygame', 'random', 'time', 'math', 'sys', 'os', 'game_funcs', 'game_files_loader', 'player', 'prey', 'hunger_bar'],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)  # type: ignore

exe = EXE(  # type: ignore
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='Circle_Nom',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=['image/others/icon.ico'],
)