# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['Circle_Nom.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('images/icon.ico', 'images'),
        ('sounds/nom_1.wav', 'sounds'),
        ('sounds/nom_2.wav', 'sounds'),
        ('sounds/nom_3.wav', 'sounds'),
        ('sounds/nom_4.wav', 'sounds'),
        ('sounds/nom_5.wav', 'sounds'),
        ('sounds/theme_song_1.wav', 'sounds'),
        ('sounds/theme_song_2.wav', 'sounds'),
        ('sounds/theme_song_3.wav', 'sounds'),
        ('sounds/theme_song_4.wav', 'sounds'),
        ('sounds/theme_song_5.wav', 'sounds'),
        ('images/background_image_1.jpg', 'images'),
        ('images/background_image_2.jpg', 'images'),
        ('images/background_image_3.jpg', 'images'),
        ('images/glowing_sandwich.png', 'images'),
        ('images/prey_image_1.png', 'images'),
        ('images/prey_image_2.png', 'images'),
        ('images/prey_image_3.png', 'images'),
        ('images/prey_image_4.png', 'images'),
        ('images/prey_image_5.png', 'images'),
        ('images/prey_image_6.png', 'images'),
        ('images/prey_image_7.png', 'images'),
        ('images/prey_image_8.png', 'images'),
        ('images/prey_image_9.png', 'images'),
        ('images/prey_image_10.png', 'images'),
        ('images/player_image_1.png', 'images'),
        ('images/player_image_2.png', 'images'),
        ('images/player_image_3.png', 'images'),
        ('images/player_image_1_dead.png', 'images'),
        ('images/player_image_2_dead.png', 'images'),
        ('images/player_image_3_dead.png', 'images'),
    ],
    hiddenimports=['pygame', 'gif_pygame', 'random', 'time', 'math', 'sys', 'os', 'game_funcs'],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='Circle_Nom',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=['images/icon.ico'],
)
